dist: trusty
language:
- php
php:
- 5.6.4
addons:
  browserstack:
    username: rtcamp2
    access_key:
before_install:
- rm -rf ~/.gnupg
before_script:
- export PLUGIN_DIR=$(pwd)
- sudo rm -rf /etc/mysql/
- sudo apt-get -qq purge mysql* graphviz* && sudo apt-get -qq autoremove
- sudo bash -c 'echo -e "[user]\n\tname = abc\n\temail = root@localhost.com" > /home/travis/.gitconfig'
- wget -qO ee rt.cx/ee && sudo bash ee
- sudo ee site create test.rtmedia.me --wp --user=ADMINUSER --email=krupa.nanda@rtcamp.com
  --pass=ADMINPASS
- sudo sed -i '/^127.0.0.1/ s/$/ test.rtmedia.me/' /etc/hosts
- sudo chmod 777 -R /var/www
- cd /var/www/test.rtmedia.me/htdocs/wp-content/plugins/ && mkdir rtMedia
- cd $PLUGIN_DIR
- cp -Rf * /var/www/test.rtmedia.me/htdocs/wp-content/plugins/rtMedia/
- cd /var/www/test.rtmedia.me/htdocs/
- wp --allow-root plugin install https://downloads.wordpress.org/plugin/buddypress.2.8.2.zip
- wp plugin activate --all
- cd $PLUGIN_DIR
- cd tests/codeception/tests/_data
- git clone --depth=1 https://github.com/rtCamp/rtmedia-test-data.git test-data
- cd /tmp
- sudo apt-get install unzip && unzip BrowserStackLocal-linux-x64.zip
# - nohup ./BrowserStackLocal --key  &
- cd $PLUGIN_DIR/tests/codeception/
- composer install
- export PATH="$PATH:/home/travis/build/kjnanda/rtMedia/tests/codeception/vendor/bin"
script:
- wpcept run acceptance
env:
  global:
    secure: X+n7bl2QuGQhRMIwEMm5DYkh9JIamqqvmTxgN8lNBdvBuiNcmwBW/OoOyDdZ9rGkC6HAa5odLJEBU+WmUH1ciD7RhPNhAUTTpgw10LPuET0JLNA+HzX4d3+T/5ZoVmVcvYZL2ZNQ4mvkGoCA7uHr1CvrkkRxh8iEypQemTWX353HprvKsz9qUQjMddvLahetL62uJqwVoogmifudicZ2UrRJTPWzB4WePRwbaeFxRTXcqpCdQ8LHT/aZBSUtIM/o7S4UQEzoxv+Y/Yy38IUhoy7EPpbtCERQNu8NWM99KVeG1PBNYJUpWDL9qN6WsTrmaPROqbTB9wAmFMNO9V4S1/96+5uqcGzGAPvo5GCAds8WXhsEMXHxrQMy8rl4U0Fo3iHw0IxmShN8P+8qoPwLg7ISHZfGDgOd+5WA4wGbCFiwtBmvmVSAH6RBrGUv2TxfCg5h7hfDjLy9Pur69kuFLBRm/504mKGelGpAO6C9IOzorFVFVORA7HVbzGzo9L6ycRiLoWmhHC0LdZPageKd6OOsbbk13BraFkZXHkWq8X4yFGusqPOyDp65YipcSi9Qgi/4PVbNry8QeBRzJGmmNhT5UB7orYs8q7BQtLBYAhglV5r0OcgA6ydxZCV2X5fZLYhFq1CJki+q808fhaTAjDpaqjSrkRqZHCdcz71dK34=
