dist: trusty

language:
    - php
php:
    - 5.6.4

# env:
#
# - TEST_SUITE=01-Privacy
# - TEST_SUITE=02-Display
# - TEST_SUITE=03-Buddypress
# - TEST_SUITE=04-MediaSizes
# - TEST_SUITE=05-Types
# - TEST_SUITE=06-CustomCss
# - TEST_SUITE=07-OtherSettings

addons:
  browserstack:
    username: rtcamp2
    access_key:
        secure: ihCEPLoMebqjwSClzlLDYohFeevLSOD9gNfcIgKLxlmWmjq6a5WZwsLQ6Z9wWkJJSGYKvvwkeLa+PNUfF8hqvtWIPFDeXsWgujc+/6cizxgJexF4fd7wic78xHaffozb0Fk53tk7ATwuaEi3e9Lcr8SR30aML+X41x3xfsN6o5+lzGmkZJO2VgcJafcCwQr8achxTiK2i0OpTaPoYUMM5PiGtRAZRN7JbL/dcQhYbtux1OOX3jswczmISbnIPoxOf30fuRs0uKHW4nVNLB3KuaSOfwgpwMttzpC3osrM7HZiNA+K5iwJwlPrZwhW8R5S50UyjVtvDtacSu63h5ffWRigr2fDnbG7CEhMsUfEz3boH/f4U6M+GjP4xRG9DXRuP/rSyGOjiXlP5MxmziBKEvNP2CETcDcl32pNfykEF835DbUWBueVUY+tPFFEtxfnqeNa4TVXGRLtpMU++hLQUsQq1sBfE7AuI5Kb9VOxVFHfZJthMHhQAZz03mky8nL7UKpuxlnS8L1yWpV8CiHDBCuNEruK6YR3ckIHF8GLSa6dVK87NWWFQocQ3Rnb6hACid0dexkywPpwkT5RZstBc0mdX4kduGbM6CmIFdgMjp0+e3UfuI4ofq8vIQBCof1siItqoGbNE+IpWMXHr7IgCJAercSSd0dM4Txi1Bo/xoY=

before_install:
- rm -rf ~/.gnupg

cache:
  paths:
  - vendor/

before_script:
- export PLUGIN_DIR=$(pwd)
- sudo rm -rf /etc/mysql/
- sudo apt-get -qq purge mysql* graphviz* && sudo apt-get -qq autoremove
- sudo bash -c 'echo -e "[user]\n\tname = abc\n\temail = root@localhost.com" > /home/travis/.gitconfig'
- wget -qO ee rt.cx/ee && sudo bash ee
- sudo tail /var/log/ee/ee.log
- sudo ee site create test.rtmedia.me --wp --user=ADMINUSER --email=krupa.nanda@rtcamp.com --pass=ADMINPASS
- sudo sed -i '/^127.0.0.1/ s/$/ test.rtmedia.me/' /etc/hosts
- sudo chmod 777 -R /var/www
- cd /var/www/test.rtmedia.me/htdocs/wp-content/plugins/ && mkdir rtMedia
- cd $PLUGIN_DIR
- cp -Rf * /var/www/test.rtmedia.me/htdocs/wp-content/plugins/rtMedia/
- cd /var/www/test.rtmedia.me/htdocs/
- wp --allow-root plugin install https://downloads.wordpress.org/plugin/buddypress.2.8.2.zip
- wp plugin activate --all
- cd /var/www/test.rtmedia.me/htdocs/wp-content/themes/
- wp theme activate twentysixteen
- cd $PLUGIN_DIR
- cd tests/codeception/tests/_data
- git clone --depth=1 https://github.com/rtCamp/rtmedia-test-data.git test-data
- cd /tmp
- wget http://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip
- unzip BrowserStackLocal-linux-x64.zip
- nohup ./BrowserStackLocal --key $BROWSERSTACK_ACCESS_KEY &
- cd $PLUGIN_DIR/tests/codeception/
- composer install
- export PATH="$PATH:/home/travis/build/kjnanda/rtMedia/tests/codeception/vendor/bin"

script:

# - if [ "$TEST_SUITE" = "01-Privacy" ]; then wpcept run tests/acceptance/core-rtMedia-settings/01-Privacy/; fi
#
# - if [ "$TEST_SUITE" = "02-Display" ]; then wpcept run tests/acceptance/core-rtMedia-settings/02-Display/; fi
#
# - if [ "$TEST_SUITE" = "03-Buddypress" ]; then wpcept run tests/acceptance/core-rtMedia-settings/03-Buddypress/; fi
#
# - if [ "$TEST_SUITE" = "04-MediaSizes" ]; then wpcept run tests/acceptance/core-rtMedia-settings/04-MediaSizes/; fi
#
# - if [ "$TEST_SUITE" = "05-Types" ]; then wpcept run tests/acceptance/core-rtMedia-settings/05-Types/; fi
#
# - if [ "$TEST_SUITE" = "06-CustomCss" ]; then wpcept run tests/acceptance/core-rtMedia-settings/06-CustomCss/; fi
#
# - if [ "$TEST_SUITE" = "07-OtherSettings" ]; then wpcept run tests/acceptance/core-rtMedia-settings/07-OtherSettings/; fi

- wpcept run tests/acceptance/core-rtMedia-settings/01-Privacy/
- wpcept run tests/acceptance/core-rtMedia-settings/02-Display/
- wpcept run tests/acceptance/core-rtMedia-settings/03-Buddypress/
- wpcept run tests/acceptance/core-rtMedia-settings/04-MediaSizes/
- wpcept run tests/acceptance/core-rtMedia-settings/05-Types/
