dist: trusty

language:
    - php
php:
    - 5.6.4

addons:
  browserstack:
#    username: rtcamp2
    username: "satinder5"
    access_key: "yABGeCxEUBLqARqvxmUP"
#      secure: yABGeCxEUBLqARqvxmUP
#        secure: co0cs4Anst7BQJUS7NL0luIvlkD3h9Z0ErtrflhENnju7/NGMvgSPxwLXlkPBefTeeCsvkcnNoN04MUbMYfo4tQgsHWm3HSPk18UTCD6KOaIvhUE08dn1EfqHN2tdN3/P0n/SGwS5xXbz6yzdcQOwALtnM7Mh9Dt34ij2VdWohLhZQWQrttYbjC2xPju0UMXyfz88WH4b8V6aSWC7JTsNDZEElpa0l2GgnID/DIPJEu3KLtGI8vfFgoIumaiuTZZPdx49XQaHmLRdy5B8+DJq33049UBchoTbqVteao0XgTOe8jSJ3r3jfYhrxMQuz+5JaTwxXREjT8wgc3JUH0o0yrFY6sEiuRrU7bQeUg11Xw/E7H14yYEedh43R7yoeVeNmtISGQJGS4wREFiOxKHrErvLQNaSIuHYnl/D6/14++ZJ9qZ/OwXcAwkePxHJRggqgOXrMtmjFUigICMcoFRpWcozBG+iY2qb9SQLMaHQzqKahfFj+3MCchtlSkFrbh7H8tE49ytw1F1aidNzGnWinz6p6fRS+BnWPdRVEktvLLV30uv0Xb4kmnwqbvhdpphfhHeVMoZd81m/iKXNWuXkO0TPtBv/vTkEaEOUcqDKq3soeekhZo+JHxirjM+xwFJmvz4oqwED68Hhsh6nPj4QYXW25X7hR6KFyad6s1c9Mk=


before_install:
- rm -rf ~/.gnupg

cache:
  paths:
  - vendor/

before_script:
- export PLUGIN_DIR=$(pwd)
- sudo rm -rf /etc/mysql/
- sudo apt-get -qq purge mysql* graphviz* && sudo apt-get -qq autoremove
- sudo bash -c 'echo -e "[user]\n\tname = abc\n\temail = root@localhost.com" > /home/travis/.gitconfig'
- wget -qO ee rt.cx/ee && sudo bash ee
- sudo tail /var/log/ee/ee.log
- sudo ee site create sumeet.rtmedia.me --wp --user=ADMINUSER --email=sumeet.sarna@rtcamp.com --pass=ADMINPASS
- sudo sed -i '/^127.0.0.1/ s/$/ test.rtmedia.me/' /etc/hosts
- sudo chmod 777 -R /var/www
- cd /var/www/sumeet.rtmedia.me/htdocs/wp-content/plugins/ && mkdir rtMedia
- cd $PLUGIN_DIR
- cp -Rf * /var/www/sumeet.rtmedia.me/htdocs/wp-content/plugins/rtMedia/
- cd /var/www/sumeet.rtmedia.me/htdocs/
- wp --allow-root plugin install https://downloads.wordpress.org/plugin/buddypress.2.8.2.zip
- wp plugin activate --all
- cd /var/www/sumeet.rtmedia.me/htdocs/wp-content/themes/
- wp theme activate twentysixteen
- cd $PLUGIN_DIR
- cd tests/codeception/tests/_data
- git clone --depth=1 https://github.com/rtCamp/rtmedia-test-data.git test-data
- cd /tmp
- wget http://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip
- unzip BrowserStackLocal-linux-x64.zip
- nohup ./BrowserStackLocal --key $BROWSERSTACK_ACCESS_KEY &
- cd $PLUGIN_DIR/tests/codeception/
- composer install
#- export PATH="$PATH:/home/travis/build/kjnanda/rtMedia/tests/codeception/vendor/bin"

script:
- wpcept run tests/acceptance/core-rtMedia-settings/01-Types/01-Negative/
- wpcept run tests/acceptance/core-rtMedia-settings/01-Types/02-Positive/
- wpcept run tests/acceptance/core-rtMedia-settings/02-Display/01-Positive/
- wpcept run tests/acceptance/core-rtMedia-settings/02-Display/02-Negative/
- wpcept run tests/acceptance/core-rtMedia-settings/03-Buddypress/01-Positive/
- wpcept run tests/acceptance/core-rtMedia-settings/03-Buddypress/02-Negative/
- wpcept run tests/acceptance/core-rtMedia-settings/04-MediaSizes/01-Postive/
- wpcept run tests/acceptance/core-rtMedia-settings/04-MediaSizes/02-Negative/
- wpcept run tests/acceptance/core-rtMedia-settings/05-Privacy/01-Positive/
- wpcept run tests/acceptance/core-rtMedia-settings/05-Privacy/02-Negative/
- wpcept run tests/acceptance/core-rtMedia-settings/06-CustomCss/01-Positive/
- wpcept run tests/acceptance/core-rtMedia-settings/06-CustomCss/02-Negative/
- wpcept run tests/acceptance/core-rtMedia-settings/07-OtherSettings/01-Positive/
- wpcept run tests/acceptance/core-rtMedia-settings/07-OtherSettings/02-Negative/
