language: php
php:
  - 5.5

before_install:
  - rm -rf ~/.gnupg
  - sudo apt-get install xvfb

cache:
  paths:
  - vendor/

before_script:
  ## PHP_CodeSniffer
  - pear install pear/PHP_CodeSniffer
  - git clone git://github.com/wimg/PHPCompatibility.git $(pear config-get php_dir)/PHP/CodeSniffer/Standards/PHPCompatibility
  - phpenv rehash
  - phpcs -i
  - phpenv rehash
  - phpcs --config-set error_severity 1
  - phpcs --config-set warning_severity 0
  ## Install composer
  - apt-get update && apt-get install -qqy git unzip
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  - composer install

script:
  ## PHP_CodeSniffer
  - phpcs --standard=PHPCompatibility --runtime-set testVersion 5.3-5.5 $(find ./ -name '*.php')
  - if find . -name "*.php" ! -path "./node_modules/*" -exec php -l {} 2>&1 \; | grep "syntax error, unexpected"; then exit 1; fi
  # Run codeceptin test
  - ./vendor/bin/codecept run test/acceptance/core-rtMedia-settings/tests/codeception/tests/acceptance/core-rtMedia-settings/display/negative-testcases/ng-allow-user-commentonuploadedMediaCept.php
notifications:
  slack:
    secure: E9tbxOZ/n4Gcwi8SiCKQ5QVw+5AfwdTq4e/VG4epQF74IqXmJJvaJgQSVKLSVXJm4O1u8JHd+ffN1Xheh1FDaKkscuJYQcT4D+oOc40bHhb0tS71v1fAMzMX7NuyqgEu2a8dbYo7bqVKtdj/EBbOPWnwgfMuA6ylTItVf294spA=
