dist: trusty

language:
    - php

branches:
  only:
    - codeception
php:
    - 5.6.4
#    - 7.0

addons:
  browserstack:
    username: "potential3"
    access_key:
     secure: "kzxBsdQ6YlCwSmNiRUySajSsy+WSgFFW25ZACPxIyZ+nhhqDFrJe6G8APU6ICcLbZC1FAJ6oMCqvl462a+j7L+/ku5WyA5EW9iTWr8Nw1gIB22EAvPaVVyUvAdW/WTNFvEttfSGud/9Pf16ACyjL3z7xaoa3C/rRFqHSBpnb+mycuGc0EJ1V778vAzkUCFUh6irtBoTZPrYMUaM3ayoeapkwmGnNEpb+ws4Mhcqv+LP12iWW6LkhcONR0WS5+DZI9Ig4r/aGdAq+wbEozRr63el6pK2wCS3WHbQtu/kHQAZ/2c9TYPGiuqFBZpSatYl5nj+VnRBGrLuGASM9Dp8QsoWfGqWYzsYkmGXanMXKyCOxlfC74zQdjtRpyhcFok14dCEMK0mt6MOHTo0VIgDLecJJTFQmXO273QdfCGePzQ+wCFIHIEtf6v/D2h4hYGCPZt0sszV+QQic72ts4/gW15r4SXZaRhI0jMKQ9sqiwNbRYJ1QRpljAKEWBZN+ObVcV6Ee/v2vnkh15oYgnDFoXa0rUaDINrYXTu/u5jVLY/WkqiOOiZQVI5AAaNgHsQMolQCR6YqX33cRDQT8rFi3e2o6ZWEZKlmYLqLo8+QUDWe0+wDjHZ1zit9OlYSEVZqDrDMi9roGY0eDk5/WlDgtZQP/kcYF6bgnuASg8sws5ck="




before_install:
- rm -rf ~/.gnupg


cache:
  paths:
  - vendor/

before_script:
- export PLUGIN_DIR=$(pwd)
- sudo rm -rf /etc/mysql/
- sudo apt-get -qq purge mysql* graphviz* && sudo apt-get -qq autoremove
- sudo bash -c 'echo -e "[user]\n\tname = abc\n\temail = root@localhost.com" > /home/travis/.gitconfig'
- wget -qO ee rt.cx/ee && sudo bash ee
- sudo apt-get update
- sudo tail /var/log/ee/ee.log
- sudo ee site create sumeet.rtmedia.me --wp --user=ADMINUSER --email=sumeet.sarna@rtcamp.com --pass=ADMINPASS
- sudo sed -i '/^127.0.0.1/ s/$/ sumeet.rtmedia.me/' /etc/hosts
- sudo chmod 777 -R /var/www
- cd /var/www/sumeet.rtmedia.me/htdocs/wp-content/plugins/ && mkdir rtMedia
- cd $PLUGIN_DIR
- cp -Rf * /var/www/sumeet.rtmedia.me/htdocs/wp-content/plugins/rtMedia/
- cd /var/www/sumeet.rtmedia.me/htdocs/
- wp --allow-root plugin install https://downloads.wordpress.org/plugin/buddypress.2.8.2.zip
- wp plugin activate --all
- cd /var/www/sumeet.rtmedia.me/htdocs/wp-content/themes/
- wp theme activate twentysixteen
- cd $PLUGIN_DIR
- cd tests/codeception/tests/_data
- git clone --depth=1 https://github.com/rtCamp/rtmedia-test-data.git test-data
- cd /tmp
- wget http://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip
- unzip BrowserStackLocal-linux-x64.zip
- nohup ./BrowserStackLocal --key $BROWSERSTACK_ACCESS_KEY &
- cd $PLUGIN_DIR/tests/codeception/
- composer update
#- export PATH="$PATH:/home/travis/build/sumeetsarna/rtMedia/tests/codeception/vendor/bin"

script:
- vendor/bin/wpcept run tests/acceptance/core-rtMedia-settings/02-Display/01-Positive/ --steps
#- vendor/bin/wpcept run tests/acceptance/core-rtMedia-settings/02-Display/02-Negative/ --steps
#- vendor/bin/wpcept run tests/acceptance/core-rtMedia-settings/01-Types/01-Negative/ --steps
#- vendor/bin/wpcept run tests/acceptance/core-rtMedia-settings/01-Types/02-Positive/ --steps
#- vendor/bin/wpcept run tests/acceptance/core-rtMedia-settings/03-Buddypress/01-Positive/ --steps
#- vendor/bin/wpcept run tests/acceptance/core-rtMedia-settings/03-Buddypress/02-Negative/ --steps
#- vendor/bin/wpcept run tests/acceptance/core-rtMedia-settings/04-MediaSizes/01-Postive/  --steps
#- vendor/bin/wpcept run tests/acceptance/core-rtMedia-settings/04-MediaSizes/02-Negative/ --steps
#- vendor/bin/wpcept run tests/acceptance/core-rtMedia-settings/05-Privacy/01-Positive/ --steps
#- vendor/bin/wpcept run tests/acceptance/core-rtMedia-settings/05-Privacy/02-Negative/ --steps
#- vendor/bin/wpcept run tests/acceptance/core-rtMedia-settings/06-CustomCss/01-Positive/ --steps
#- vendor/bin/wpcept run tests/acceptance/core-rtMedia-settings/06-CustomCss/02-Negative/ --steps
#- vendor/bin/wpcept run tests/acceptance/core-rtMedia-settings/07-OtherSettings/01-Positive/ --steps
#- vendor/bin/wpcept run tests/acceptance/core-rtMedia-settings/07-OtherSettings/02-Negative/ --steps
