dist: trusty

language:
    - php
php:
  - 5.6.4

before_install:
  - rm -rf ~/.gnupg

before_script:
  - export PLUGIN_DIR=$(pwd)
  - sudo rm -rf /etc/mysql/
  - sudo apt-get -qq purge mysql* graphviz*
  - sudo apt-get -qq autoremove
  - sudo bash -c 'echo -e "[user]\n\tname = abc\n\temail = root@localhost.com" > /home/travis/.gitconfig'
  - wget -qO ee rt.cx/ee && sudo bash ee
  - source /etc/bash_completion.d/ee_auto.rc
  - sudo apt-get clean && sudo apt-get clean all && sudo apt-get update
  - sudo ee site create rtmedia.localtest.me --wp --user=ADMINUSER --email=krupa.nanda@rtcamp.com --pass=ADMINPASS || true
  - sudo apt-get update || true
  # Remove || true in above line after debugging
  - sudo cat /var/log/ee/ee.log
  - sudo chmod 777 -R /var/www
  - sudo cat /etc/mysql/conf.d/my.cnf
  # - sudo cat ~/.my.cnf
  - sudo nginx -t
  - sudo service nginx reload
  - cd /var/www/rtmedia.localtest.me/htdocs/wp-content/plugins/ && ls
  - mkdir rtMedia
  - cd $PLUGIN_DIR
  - cp -Rf * /var/www/rtmedia.localtest.me/htdocs/wp-content/plugins/rtMedia/
  - cd /var/www/rtmedia.localtest.me/htdocs/
  - wp --allow-root plugin install https://downloads.wordpress.org/plugin/buddypress.2.8.2.zip
  # - wp --allow-root plugin install https://downloads.wordpress.org/plugin/buddypress-media.4.3.1.zip
  - wp plugin activate --all
  - cd $PLUGIN_DIR
  - cd tests/codeception/tests/_data
  - git clone --depth=1 https://github.com/rtCamp/rtmedia-test-data.git test-data

  # Navigate to codeception directory
  - cd $PLUGIN_DIR/tests/codeception/

  # Install all project dependencies
  - composer install
  - export PATH="$PATH:/home/travis/build/kjnanda/rtMedia/tests/codeception/vendor/bin"


# install:
# #install codeception for wordpress
# - composer require lucatume/wp-browser --dev


script:
  ## PHP_CodeSniffer
  # - phpcs --standard=PHPCompatibility --runtime-set testVersion 5.3-5.5 $(find ./ -name '*.php')
  # - if find . -name "*.php" ! -path "./node_modules/*" -exec php -l {} 2>&1 \; | grep "syntax error, unexpected"; then exit 1; fi
  # Run codeception test
  - ./vendor/bin/codecept run test/acceptance/core-rtMedia-settings
# notifications:
#   slack:
#     secure: E9tbxOZ/n4Gcwi8SiCKQ5QVw+5AfwdTq4e/VG4epQF74IqXmJJvaJgQSVKLSVXJm4O1u8JHd+ffN1Xheh1FDaKkscuJYQcT4D+oOc40bHhb0tS71v1fAMzMX7NuyqgEu2a8dbYo7bqVKtdj/EBbOPWnwgfMuA6ylTItVf294spA=
