dist: trusty
language: php
sudo: required
php:
  - 5.5
branches:
  only:
    - codeception

before_install:
  - rm -rf ~/.gnupg
  - sudo apt-get install xvfb

addons:
  browserstack:
    username: rtcamp3
    access_key:
     secure: "tXH9xnJHYSL3NAnvMHRL9/PYe/FY3u4+Ws3lU3GmeArZkHSdrtfyOeyvwZGFI4HUBSv9l5lKOWoTFsk2y5/PDnJdTuwabuI2QGBSs0TBgqEG44NEX6VFTZtmMKUFLkKAHA44I+z8ZG+xi82yESs8XyEDbcRpRh0KLFVVMJQPgwKIH9dqZyMuYzDGndr7tWnW+BZvlqF4uhMFPU7/FNtp8+u1LcPxMgxgnS5gQYHxgrd32gomhCFNlYsxJkU4G53VPHnUS4n5E337vN+l3FH+EdoDAu7eNNwMsQOLexD6Wo3I8VVQa5Y/omaparyKuTxJFarpY9wZm3FMwTWh0w15SZWzSWpTc/YKFrNFT6+G+14akIZkYPpTggkQ7e/AcJGOw705phP2Pl37rwLBo9RTR7u6B8MwXY4IEo3TBiZ1SQt8nAo5NcZajaJl5YPdAT/wqSgGQSi3w4rGrAEjZd8MiGG6RRWQ61gSDFf8i9d8j13dhBXK4pr4RT1KSJN+YHRVlw/LwvVH4ZQQ88RHr77KA+AnV2u0FyX0PromEDwov0QZLuBx9TM3iFZ5H3j5QsI7fsQUJgViofJxB3+t7YsgmB20+kPM/3RuIUwlGHhz7VyZkHyOI4GMzWPJMlelKdS7hqTI9QVbnX1vMJceKHCagZDSvGKy8YWXS9NB5E+ejrU="

before_script:
  - export PLUGIN_DIR=$(pwd)
  - sudo rm -rf /etc/mysql/
  - sudo apt-get -qq purge mysql* graphviz* && sudo apt-get -qq autoremove
  - sudo bash -c 'echo -e "[user]\n\tname = abc\n\temail = root@localhost.com" > /home/travis/.gitconfig'
  - wget -qO ee rt.cx/ee && sudo bash ee
  - sudo apt-get update
  - sudo tail /var/log/ee/ee.log
  - sudo ee site create automation.rtmedia.me --wp --user=ADMINUSER --email=umesh.nevase@rtcamp.com --pass=ADMINPASS
  - sudo sed -i '/^127.0.0.1/ s/$/ automation.rtmedia.me/' /etc/hosts
  - sudo chmod 777 -R /var/www
  - cd /var/www/automation.rtmedia.me/htdocs/wp-content/plugins/ && mkdir rtMedia
  - cd $PLUGIN_DIR
  - cp -Rf * /var/www/automation.rtmedia.me/htdocs/wp-content/plugins/rtMedia/
  - cd /var/www/automation.rtmedia.me/htdocs/
  - wp --allow-root plugin install https://downloads.wordpress.org/plugin/buddypress.2.8.2.zip
  - wp plugin activate --all
  - cd /var/www/automation.rtmedia.me/htdocs/wp-content/themes/
  - wp theme activate twentysixteen
  - cd $PLUGIN_DIR
  - cd tests/codeception/tests/_data
  - git clone --depth=1 https://github.com/rtCamp/rtmedia-test-data.git test-data
  - cd /tmp
  - wget http://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip
  - unzip BrowserStackLocal-linux-x64.zip
  - nohup ./BrowserStackLocal --key $BROWSERSTACK_ACCESS_KEY &
  - cd $PLUGIN_DIR/tests/codeception/
  - composer update
  - export PATH="$PATH:/home/travis/build/rtMediaWP/rtMedia/tests/codeception/vendor/bin"
  ## PHP_CodeSniffer
  - pear install pear/PHP_CodeSniffer-2.9.0
  - git clone git://github.com/wimg/PHPCompatibility.git $(pear config-get php_dir)/PHP/CodeSniffer/Standards/PHPCompatibility
  - phpenv rehash
  - phpcs -i
  - phpenv rehash
  - phpcs --config-set installed_paths $(pear config-get php_dir)/PHP/CodeSniffer/Standards
  - phpcs --config-set error_severity 0
  - phpcs --config-set warning_severity 0

script:
  ## PHP_CodeSniffer
  - phpcs --standard=PHPCompatibility --runtime-set testVersion 5.3-5.5 $(find ./tests/acceptance -name '*.php')
  - if find . -name "*.php" ! -path "./node_modules/*" ! -path "./vendor/*" -exec php -l {} 2>&1 \; | grep "syntax error, unexpected"; then exit 1; fi
  - codecept run acceptance --steps