dist: trusty

language:
    - php
php:
  - 5.6.4

addons:
  browserstack:
    username: '%BS_USERNAME'
    access_key: '%BS_KEY'
    #   secure: "QSmlliOJwnUtjXQFrTJK0PlKKzK+xRNHTjcI2p3+6bafopV6acOzS6E9n8XIyKIxS/8YUNinQwI3SsCVKEJbBaC1pNLDhwXACqSQQzFcTn/yoCVVBRIXCEPapkdZh70l0PLVIJYaAVXG0OjQykAL90HE1wOs1G+DDfOMcJWUTUpGUKHcu8AYv/6/ynJnzHS1/wWdE5br7cqOqnVbdeRlc9i5KiLvI2LZ6rGOCBjCQ7aq15PlipoPZntQQMNEOapfBb+gIGTuvz+uLzm3SMLBhF6hNQzXDV8mw7AQCXcDGZobFXQlItMUwpeNG5Jf6mK7JI1fo3fNPi2D/uTUCGpwu60Ey3ROfwgW26KFxPxcXe7aTbO/RaK19dfybFKW5a/1HkcC6QhVSSF0QzFc4pbG34ilMciGP6EeoyjFEz5/uNKqllJh2WvB6xQ24vIwG+gvVXi+ju3tZa3mKcDRkkpGhaFwJFkhomIhxUqaCWJ5g+HSNu8zerbhpnCKwlgZga/rRg6PnQBgkzmlB5nz7nnmxWATsiuWxzOmzWPGxQwE+x74zMAmG3THw9E7vXI2pa4HNE8lY37x2xAQtiKs6xtbA8Nx/Cy6d5MlJzNVVUrFhfl6EggNPytwli+Ny8tzMqIdL8PNeP0l15EwOp5rv6IsTzrM5BmCCtIOCozjdAGeQJA="



before_install:
  - rm -rf ~/.gnupg

before_script:
  - export PLUGIN_DIR=$(pwd)
  - sudo rm -rf /etc/mysql/
  - sudo apt-get -qq purge mysql* graphviz* && sudo apt-get -qq autoremove
  - sudo bash -c 'echo -e "[user]\n\tname = abc\n\temail = root@localhost.com" > /home/travis/.gitconfig'
  - wget -qO ee rt.cx/ee && sudo bash ee
  - sudo ee site create test.rtmedia.me --wp --user=ADMINUSER --email=krupa.nanda@rtcamp.com --pass=ADMINPASS
  - sudo sed -i '/^127.0.0.1/ s/$/ test.rtmedia.me/' /etc/hosts
  - sudo chmod 777 -R /var/www
  - cd /var/www/test.rtmedia.me/htdocs/wp-content/plugins/ && mkdir rtMedia
  - cd $PLUGIN_DIR
  - cp -Rf * /var/www/test.rtmedia.me/htdocs/wp-content/plugins/rtMedia/
  - cd /var/www/test.rtmedia.me/htdocs/
  - wp --allow-root plugin install https://downloads.wordpress.org/plugin/buddypress.2.8.2.zip
  - wp plugin activate --all
  - cd $PLUGIN_DIR
  - cd tests/codeception/tests/_data
  - git clone --depth=1 https://github.com/rtCamp/rtmedia-test-data.git test-data
  - cd /tmp
  - sudo apt-get install unzip && unzip BrowserStackLocal-linux-x64.zip
  - nohup ./BrowserStackLocal --key $BS_KEY &
  - cd $PLUGIN_DIR/tests/codeception/
  - composer install
  - export PATH="$PATH:/home/travis/build/kjnanda/rtMedia/tests/codeception/vendor/bin"

script:
  - wpcept run acceptance

# notifications:
#   slack:
#     secure: kwDatt2QkPShzntf0etxD/KOZSXS4VO2qGxj7crmJoAovvlvzjSZrfkqE4FuOo3annhx9ZO/APIoooaxEMvMmKekafOMTSPd3SzjF/tN8pZAn/l07GRvKqwqox2kjwNLj/HzHr4wP/kRFcYePYjZN0pU3LFTfSx0y592b6Wwc9I/qk02CjYVnUhnh32MUZ+5jALI6BR9jjVaWzlSPbqutQVkUNEFKWf8RVI0zCRRNW2aZAl426H6p8YnJWZ4Jr5HF4hIlx5pkPzR8sPnKU3o+xYho14iWzhsiGDUtmRG/SWu6Qf/P7sDVTm5/SsFbv6Xh1PiTNpBUB8YIGvLkXrZo4NFvJRlh0io1JpNHkPZ/NY1Sr3P7wm9BSCB+9I5eaa7fpAOXaSzec22I6mqRgMNJhnr+SgWCPrbjPm+NGP3KkIMbr4ulPMHmKIuGmk5h09p+/0RPSoQItNFnma1Uo+21XWvyBa8/498+aKqlNvNeTJ3nVIUn7FaoOzr2oiR+1Eu8hbE7efynBHoGgA0T1oXM2r6RtF7tKbUvMv4YRrcUy5sfyDVLY4OduD1PMKCKVy62xGTlcKwIVEqwobDksqe92pP54yAp+dYlhLNWqacHjjq1LD5qBASmZ2DwrYZvXKmmEmU6cmgED3h7r0/BtE2Y2BJsF3NiYiYqt0PAm6UFBE=
